server:
  port: 0 # port random

spring:
  application:
    name: user-service

eureka:
  instance:
    instance-id: user-microservice-instance
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://admin:admin@localhost:8761/eureka
      defaultZone: http://localhost:8761/eureka
